# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80231d01dfcd1c807b07c52d2a1dfa4875b022a8221cb0f795aa23ed19abf02a8142709c9303f69f444de42f3758645e40dbdf52a8231b2d7c8c82d345e25b62

test:
  secret_key_base: ec85a336efd2145179e56bf5b20278e1855edfe4c7e835c9dc47930f44410b04d08327f4020bed0a83a8476c0364a84b10cd90a10883acbe7f9c1b7ba2bfc148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
